// Auto-generated from Tag_Ferramental_KOE.xlsx
// 236 tools — photos should be added manually via the photo field

export type ToolStatus = "Available" | "Calibration" | "In Use" | "Maintenance";
export type ToolCategory = "Tool" | "Equipment" | "PPE";
export type ToolType =
  | "Rope Access"
  | "Corded"
  | "Cordless"
  | "Electrical"
  | "Measurement"
  | "Load/Lift"
  | "Communication"
  | "Pneumatics"
  | "Manual";

export interface Tool {
  id: string;
  code: string;
  name: string;
  brand: string;
  category: string;
  type: string;
  tag: string;       // 4-digit numeric identifier
  serie: string;     // free alphanumeric serial number
  status: ToolStatus;
  qty: number;
  value: number;
  hasCalibration?: boolean;
  photo?: string;    // URL or base64 — added manually
}

export const TOOLS_DATA: Tool[] = [
  {
    "id": "00001",
    "code": "00001",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0001",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00002",
    "code": "00002",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0002",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00003",
    "code": "00003",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0003",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00004",
    "code": "00004",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0004",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00005",
    "code": "00005",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0005",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00006",
    "code": "00006",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0006",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00008",
    "code": "00008",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0008",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00009",
    "code": "00009",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0009",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00010",
    "code": "00010",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0010",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00011",
    "code": "00011",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0011",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00012",
    "code": "00012",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0012",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00013",
    "code": "00013",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0013",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00014",
    "code": "00014",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0014",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00015",
    "code": "00015",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0015",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00016",
    "code": "00016",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0016",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00017",
    "code": "00017",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0017",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00018",
    "code": "00018",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0018",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00019",
    "code": "00019",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0019",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00020",
    "code": "00020",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0020",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00021",
    "code": "00021",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0021",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00022",
    "code": "00022",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0022",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00023",
    "code": "00023",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0023",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00024",
    "code": "00024",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0024",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00025",
    "code": "00025",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0025",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00026",
    "code": "00026",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0026",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00027",
    "code": "00027",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0027",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00028",
    "code": "00028",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0028",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00029",
    "code": "00029",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0029",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00030",
    "code": "00030",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0030",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00031",
    "code": "00031",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0031",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00032",
    "code": "00032",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0032",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00033",
    "code": "00033",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0033",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00034",
    "code": "00034",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0034",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00035",
    "code": "00035",
    "name": "ID - DESCENSOR",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0035",
    "serie": "",
    "status": "In Use",
    "qty": 1,
    "value": 250.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00036",
    "code": "00036",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0036",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00037",
    "code": "00037",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0037",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00038",
    "code": "00038",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0038",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00039",
    "code": "00039",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0039",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00040",
    "code": "00040",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0040",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00041",
    "code": "00041",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0041",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00042",
    "code": "00042",
    "name": "JUMAR - PUNHO",
    "brand": "CTCLIMBING",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0042",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00043",
    "code": "00043",
    "name": "JUMAR - PUNHO",
    "brand": "KONG",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0043",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00044",
    "code": "00044",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0044",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00045",
    "code": "00045",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0045",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00046",
    "code": "00046",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0046",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00047",
    "code": "00047",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0047",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00048",
    "code": "00048",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0048",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00049",
    "code": "00049",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0049",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00050",
    "code": "00050",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0050",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00051",
    "code": "00051",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0051",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00052",
    "code": "00052",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0052",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00053",
    "code": "00053",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0053",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00054",
    "code": "00054",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0054",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00055",
    "code": "00055",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0055",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00056",
    "code": "00056",
    "name": "JUMAR - PUNHO",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0056",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00057",
    "code": "00057",
    "name": "JUMAR - PUNHO",
    "brand": "KONG",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0057",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00058",
    "code": "00058",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0058",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00059",
    "code": "00059",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0059",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00060",
    "code": "00060",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0060",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00061",
    "code": "00061",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0061",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00062",
    "code": "00062",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0062",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00063",
    "code": "00063",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0063",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00064",
    "code": "00064",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0064",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00065",
    "code": "00065",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0065",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00066",
    "code": "00066",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0066",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00067",
    "code": "00067",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0067",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00068",
    "code": "00068",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0068",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00069",
    "code": "00069",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0069",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00070",
    "code": "00070",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0070",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00071",
    "code": "00071",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0071",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00072",
    "code": "00072",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0072",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00073",
    "code": "00073",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0073",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00074",
    "code": "00074",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0074",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00075",
    "code": "00075",
    "name": "ASAP",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0075",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00076",
    "code": "00076",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0076",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00077",
    "code": "00077",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0077",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00078",
    "code": "00078",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0078",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00079",
    "code": "00079",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0079",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00080",
    "code": "00080",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0080",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00081",
    "code": "00081",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0081",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00082",
    "code": "00082",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0082",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00083",
    "code": "00083",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0083",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00084",
    "code": "00084",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0084",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00085",
    "code": "00085",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0085",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00086",
    "code": "00086",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0086",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00087",
    "code": "00087",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0087",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00088",
    "code": "00088",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0088",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00089",
    "code": "00089",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0089",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00090",
    "code": "00090",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0090",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00091",
    "code": "00091",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0091",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00092",
    "code": "00092",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0092",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00093",
    "code": "00093",
    "name": "CROLL",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0093",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00094",
    "code": "00094",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0094",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00095",
    "code": "00095",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0095",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00096",
    "code": "00096",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0096",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00097",
    "code": "00097",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0097",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00098",
    "code": "00098",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0098",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00099",
    "code": "00099",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0099",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00100",
    "code": "00100",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0100",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00101",
    "code": "00101",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0101",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00102",
    "code": "00102",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0102",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00103",
    "code": "00103",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0103",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00104",
    "code": "00104",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0104",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00105",
    "code": "00105",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0105",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00106",
    "code": "00106",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0106",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00107",
    "code": "00107",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0107",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00108",
    "code": "00108",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0108",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00109",
    "code": "00109",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0109",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00110",
    "code": "00110",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0110",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00111",
    "code": "00111",
    "name": "Harness",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0111",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 350.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00112",
    "code": "00112",
    "name": "Capacete - Casco",
    "brand": "N/I",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0112",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 30.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00113",
    "code": "00113",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0113",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00114",
    "code": "00114",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0114",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00115",
    "code": "00115",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0115",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00116",
    "code": "00116",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0116",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00117",
    "code": "00117",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0117",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00118",
    "code": "00118",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0118",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00119",
    "code": "00119",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0119",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00120",
    "code": "00120",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0120",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00121",
    "code": "00121",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0121",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00122",
    "code": "00122",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0122",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00123",
    "code": "00123",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0123",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00124",
    "code": "00124",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0124",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00125",
    "code": "00125",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0125",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00126",
    "code": "00126",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0126",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00127",
    "code": "00127",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0127",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00128",
    "code": "00128",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0128",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00129",
    "code": "00129",
    "name": "Capacete - Casco",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0129",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00130",
    "code": "00130",
    "name": "Grillon 4 m",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0130",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 150.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00131",
    "code": "00131",
    "name": "Grillon 4 m",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0131",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 150.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00132",
    "code": "00132",
    "name": "Grillon 4 m",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0132",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 150.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00133",
    "code": "00133",
    "name": "Grillon 4 m",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0133",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 150.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00134",
    "code": "00134",
    "name": "Grillon 4 m",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0134",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 150.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00135",
    "code": "00135",
    "name": "Assento",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0135",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00136",
    "code": "00136",
    "name": "Assento",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0136",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00137",
    "code": "00137",
    "name": "Assento",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0137",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00138",
    "code": "00138",
    "name": "Assento",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0138",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00139",
    "code": "00139",
    "name": "Polia Dupla Fixa 36Kg",
    "brand": "Signing Rock",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0139",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 65.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00140",
    "code": "00140",
    "name": "Polia Dupla Fixa 36Kg",
    "brand": "Signing Rock",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0140",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 65.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00141",
    "code": "00141",
    "name": "Polia Dupla Fixa 36Kg",
    "brand": "Signing Rock",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0141",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 65.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00142",
    "code": "00142",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0142",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00143",
    "code": "00143",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0143",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00144",
    "code": "00144",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0144",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00145",
    "code": "00145",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0145",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00146",
    "code": "00146",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0146",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00147",
    "code": "00147",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0147",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00148",
    "code": "00148",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0148",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00149",
    "code": "00149",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0149",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00150",
    "code": "00150",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0150",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00151",
    "code": "00151",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0151",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00152",
    "code": "00152",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0152",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00153",
    "code": "00153",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0153",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00154",
    "code": "00154",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0154",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00155",
    "code": "00155",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0155",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00156",
    "code": "00156",
    "name": "Bolsa 54L - Negra",
    "brand": "Equipo Vertical",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0156",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00157",
    "code": "00157",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Dexter",
    "category": "Tool",
    "type": "Corded",
    "tag": "0157",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 50.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00158",
    "code": "00158",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Dexter",
    "category": "Tool",
    "type": "Corded",
    "tag": "0158",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 50.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00159",
    "code": "00159",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Dexter",
    "category": "Tool",
    "type": "Corded",
    "tag": "0159",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 50.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00160",
    "code": "00160",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Dexter",
    "category": "Tool",
    "type": "Corded",
    "tag": "0160",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 50.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00161",
    "code": "00161",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Bosh",
    "category": "Tool",
    "type": "Corded",
    "tag": "0161",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00162",
    "code": "00162",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Bosh",
    "category": "Tool",
    "type": "Corded",
    "tag": "0162",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00163",
    "code": "00163",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Bosh",
    "category": "Tool",
    "type": "Corded",
    "tag": "0163",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00164",
    "code": "00164",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Makita",
    "category": "Tool",
    "type": "Corded",
    "tag": "0164",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00165",
    "code": "00165",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Bosh",
    "category": "Tool",
    "type": "Corded",
    "tag": "0165",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00166",
    "code": "00166",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Bosh",
    "category": "Tool",
    "type": "Corded",
    "tag": "0166",
    "serie": "",
    "status": "In Use",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00167",
    "code": "00167",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Dewalt",
    "category": "Tool",
    "type": "Corded",
    "tag": "0167",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00168",
    "code": "00168",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Bosh",
    "category": "Tool",
    "type": "Corded",
    "tag": "0168",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00169",
    "code": "00169",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Bosh",
    "category": "Tool",
    "type": "Corded",
    "tag": "0169",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00170",
    "code": "00170",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Dewalt",
    "category": "Tool",
    "type": "Corded",
    "tag": "0170",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00171",
    "code": "00171",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Dewalt",
    "category": "Tool",
    "type": "Corded",
    "tag": "0171",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00172",
    "code": "00172",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Makita",
    "category": "Tool",
    "type": "Corded",
    "tag": "0172",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00173",
    "code": "00173",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Dewalt",
    "category": "Tool",
    "type": "Corded",
    "tag": "0173",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00174",
    "code": "00174",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Dewalt",
    "category": "Tool",
    "type": "Corded",
    "tag": "0174",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00175",
    "code": "00175",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Makita",
    "category": "Tool",
    "type": "Corded",
    "tag": "0175",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00176",
    "code": "00176",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Makita",
    "category": "Tool",
    "type": "Corded",
    "tag": "0176",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00177",
    "code": "00177",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Makita",
    "category": "Tool",
    "type": "Corded",
    "tag": "0177",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00178",
    "code": "00178",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Dewalt",
    "category": "Tool",
    "type": "Corded",
    "tag": "0178",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00179",
    "code": "00179",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Makita",
    "category": "Tool",
    "type": "Corded",
    "tag": "0179",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00180",
    "code": "00180",
    "name": "Lixadeira Angular 4 1/2",
    "brand": "Bosh",
    "category": "Tool",
    "type": "Corded",
    "tag": "0180",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00181",
    "code": "00181",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Dewalt",
    "category": "Tool",
    "type": "Corded",
    "tag": "0181",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00182",
    "code": "00182",
    "name": "Lixadeira Orbital 4 1/2",
    "brand": "Makita",
    "category": "Tool",
    "type": "Corded",
    "tag": "0182",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00183",
    "code": "00183",
    "name": "Furadeira GSB 24-2",
    "brand": "Bosh",
    "category": "Tool",
    "type": "Corded",
    "tag": "0183",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00185",
    "code": "00185",
    "name": "Imã 300kg Mod.QZ1-0.3",
    "brand": "TL-Lift",
    "category": "Tool",
    "type": "Corded",
    "tag": "0185",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 150.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00186",
    "code": "00186",
    "name": "Carretel Extensão 1.5mm   50metros",
    "brand": "SuperPower",
    "category": "Tool",
    "type": "Electrical",
    "tag": "0186",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00187",
    "code": "00187",
    "name": "Carretel Extensão 1.5mm   50metros",
    "brand": "SuperPower",
    "category": "Tool",
    "type": "Electrical",
    "tag": "0187",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 60.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00188",
    "code": "00188",
    "name": "Maquina de Solda 200A",
    "brand": "STAYER",
    "category": "Tool",
    "type": "Corded",
    "tag": "0188",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 240.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00189",
    "code": "00189",
    "name": "Medidor de Espessura",
    "brand": "ELCOMETER",
    "category": "Tool",
    "type": "Measurement",
    "tag": "0189",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 1550.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00190",
    "code": "00190",
    "name": "Medidor de Umidade",
    "brand": "ELCOMETER",
    "category": "Tool",
    "type": "Measurement",
    "tag": "0190",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 890.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00191",
    "code": "00191",
    "name": "Furadeira a Bateria",
    "brand": "Dexter",
    "category": "Tool",
    "type": "Corded",
    "tag": "0191",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 75.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00192",
    "code": "00192",
    "name": "Furadeira 630W",
    "brand": "bosh",
    "category": "Tool",
    "type": "Corded",
    "tag": "0192",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 55.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00193",
    "code": "00193",
    "name": "Tifor 2 ton",
    "brand": "Topex",
    "category": "Tool",
    "type": "Load/Lift",
    "tag": "0193",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 40.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00194",
    "code": "00194",
    "name": "Maquina de Alta Pressao K7",
    "brand": "Karcker",
    "category": "Tool",
    "type": "Corded",
    "tag": "0194",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 650.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00195",
    "code": "00195",
    "name": "Robot - Caixa De Distribuição 220V",
    "brand": "Electraline",
    "category": "Tool",
    "type": "Electrical",
    "tag": "0195",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 85.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00196",
    "code": "00196",
    "name": "Robot - Caixa De Distribuição 220V",
    "brand": "Electraline",
    "category": "Tool",
    "type": "Electrical",
    "tag": "0196",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 85.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00197",
    "code": "00197",
    "name": "Aspirador 1400W 220V",
    "brand": "Cevik Pro",
    "category": "Tool",
    "type": "Corded",
    "tag": "0197",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00198",
    "code": "00198",
    "name": "Roller Coaster",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0198",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 130.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00199",
    "code": "00199",
    "name": "Roller Coaster",
    "brand": "PETZEL",
    "category": "Tool",
    "type": "Rope Access",
    "tag": "0199",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 130.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00200",
    "code": "00200",
    "name": "Medidor de Espessura",
    "brand": "UNIT",
    "category": "Tool",
    "type": "Measurement",
    "tag": "0200",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00201",
    "code": "00201",
    "name": "Carregador Radios",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0201",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00202",
    "code": "00202",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0202",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00203",
    "code": "00203",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0203",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00204",
    "code": "00204",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0204",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00205",
    "code": "00205",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0205",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00206",
    "code": "00206",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0206",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00207",
    "code": "00207",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0207",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00208",
    "code": "00208",
    "name": "Amoladora Recta",
    "brand": "Makita",
    "category": "Tool",
    "type": "Corded",
    "tag": "0208",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00209",
    "code": "00209",
    "name": "Amoladora Recta",
    "brand": "Makita",
    "category": "Tool",
    "type": "Corded",
    "tag": "0209",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 200.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00210",
    "code": "00210",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0210",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00211",
    "code": "00211",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0211",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00212",
    "code": "00212",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0212",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00213",
    "code": "00213",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0213",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00214",
    "code": "00214",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0214",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00215",
    "code": "00215",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0215",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00216",
    "code": "00216",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0216",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00217",
    "code": "00217",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0217",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00218",
    "code": "00218",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0218",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00219",
    "code": "00219",
    "name": "Walkie Talkie",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0219",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00221",
    "code": "00221",
    "name": "Carregador Radios",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0221",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00222",
    "code": "00222",
    "name": "Carregador Radios",
    "brand": "Retrevis",
    "category": "Tool",
    "type": "Communication",
    "tag": "0222",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00223",
    "code": "00223",
    "name": "Agulheiro Tipo Pistola",
    "brand": "Sempo",
    "category": "Tool",
    "type": "Pneumatics",
    "tag": "0223",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00224",
    "code": "00224",
    "name": "Agulheiro Tipo Pistola",
    "brand": "Sempo",
    "category": "Tool",
    "type": "Pneumatics",
    "tag": "0224",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00225",
    "code": "00225",
    "name": "Agulheiro Tipo Pistola",
    "brand": "Sempo",
    "category": "Tool",
    "type": "Pneumatics",
    "tag": "0225",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00226",
    "code": "00226",
    "name": "Agulheiro Tipo Pistola",
    "brand": "trelawny",
    "category": "Tool",
    "type": "Pneumatics",
    "tag": "0226",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 150.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00227",
    "code": "00227",
    "name": "Agulheiro Tipo Pistola",
    "brand": "trelawny",
    "category": "Tool",
    "type": "Pneumatics",
    "tag": "0227",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 150.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00228",
    "code": "00228",
    "name": "Picador Sicel",
    "brand": "Engersol",
    "category": "Tool",
    "type": "Pneumatics",
    "tag": "0228",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 100.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00229",
    "code": "00229",
    "name": "Agulheiro Tipo Pistola",
    "brand": "Druckluft",
    "category": "Tool",
    "type": "Pneumatics",
    "tag": "0229",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 80.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00230",
    "code": "00230",
    "name": "Furadeira a Bateria",
    "brand": "Dexter",
    "category": "Tool",
    "type": "Cordless",
    "tag": "0230",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 75.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00231",
    "code": "00231",
    "name": "Tifor 2 ton",
    "brand": "Topex",
    "category": "Tool",
    "type": "Load/Lift",
    "tag": "0231",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 40.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00232",
    "code": "00232",
    "name": "Tifor 2 ton",
    "brand": "Topex",
    "category": "Tool",
    "type": "Load/Lift",
    "tag": "0232",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 40.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00233",
    "code": "00233",
    "name": "Tifor 2 ton",
    "brand": "Topex",
    "category": "Tool",
    "type": "Load/Lift",
    "tag": "0233",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 40.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00234",
    "code": "00234",
    "name": "Tifor 2 ton",
    "brand": "Topex",
    "category": "Tool",
    "type": "Load/Lift",
    "tag": "0234",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 40.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00235",
    "code": "00235",
    "name": "LED 100W",
    "brand": "GSC",
    "category": "Tool",
    "type": "Corded",
    "tag": "0235",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 20.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00236",
    "code": "00236",
    "name": "Maquina de Lavar Alta Pressão",
    "brand": "Comet",
    "category": "Tool",
    "type": "Corded",
    "tag": "0236",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 4550.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00237",
    "code": "00237",
    "name": "Estrobo 100cm 8 mm",
    "brand": "",
    "category": "Tool",
    "type": "Load/Lift",
    "tag": "0237",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 45.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00238",
    "code": "00238",
    "name": "Estrobo 100cm 8 mm",
    "brand": "",
    "category": "Tool",
    "type": "Load/Lift",
    "tag": "0238",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 45.0,
    "hasCalibration": false,
    "photo": ""
  },
  {
    "id": "00239",
    "code": "00239",
    "name": "Estrobo 160cm 8 mm",
    "brand": "",
    "category": "Tool",
    "type": "Load/Lift",
    "tag": "0239",
    "serie": "",
    "status": "Available",
    "qty": 1,
    "value": 50.0,
    "hasCalibration": false,
    "photo": ""
  }
];
