export interface SeedTool {
  code: string;
  name: string;
  brand: string | null;
  category: string | null;
  type: string | null;
  tag: string | null;
  serie: string | null;
  status: string;
  qty: number;
  value: number;
  hasCalibration: boolean;
}

export const TOOLS_DATA: SeedTool[] = [
  {"code": "1", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0001", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "2", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0002", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "3", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0003", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "4", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0004", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "5", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0005", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "6", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0006", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "7", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0008", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "8", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0009", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "9", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0010", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "10", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0011", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "11", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0012", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "12", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0013", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "13", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0014", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "14", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0015", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "15", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0016", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "16", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0017", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "17", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0018", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "18", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0019", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "19", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0020", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "20", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0021", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "21", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0022", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "22", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0023", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "23", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0024", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "24", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0025", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "25", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0026", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "26", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0027", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "27", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0028", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "28", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0029", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "29", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0030", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "30", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0031", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "31", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0032", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "32", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0033", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "33", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0034", "serie": null, "status": "Available", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "34", "name": "ID - DESCENSOR", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0035", "serie": null, "status": "In Use", "qty": 1, "value": 250.0, "hasCalibration": false},
  {"code": "35", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0036", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "36", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0037", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "37", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0038", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "38", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0039", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "39", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0040", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "40", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0041", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "41", "name": "JUMAR - PUNHO", "brand": "CTCLIMBING", "category": "Tool", "type": "Rope Access", "tag": "0042", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "42", "name": "JUMAR - PUNHO", "brand": "KONG", "category": "Tool", "type": "Rope Access", "tag": "0043", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "43", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0044", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "44", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0045", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "45", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0046", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "46", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0047", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "47", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0048", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "48", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0049", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "49", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0050", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "50", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0051", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "51", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0052", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "52", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0053", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "53", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0054", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "54", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0055", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "55", "name": "JUMAR - PUNHO", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0056", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "56", "name": "JUMAR - PUNHO", "brand": "KONG", "category": "Tool", "type": "Rope Access", "tag": "0057", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "57", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0058", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "58", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0059", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "59", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0060", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "60", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0061", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "61", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0062", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "62", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0063", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "63", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0064", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "64", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0065", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "65", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0066", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "66", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0067", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "67", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0068", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "68", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0069", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "69", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0070", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "70", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0071", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "71", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0072", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "72", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0073", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "73", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0074", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "74", "name": "ASAP", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0075", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "75", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0076", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "76", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0077", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "77", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0078", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "78", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0079", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "79", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0080", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "80", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0081", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "81", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0082", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "82", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0083", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "83", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0084", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "84", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0085", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "85", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0086", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "86", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0087", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "87", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0088", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "88", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0089", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "89", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0090", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "90", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0091", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "91", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0092", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "92", "name": "CROLL", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0093", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "93", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0094", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "94", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0095", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "95", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0096", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "96", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0097", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "97", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0098", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "98", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0099", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "99", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0100", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "100", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0101", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "101", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0102", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "102", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0103", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "103", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0104", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "104", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0105", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "105", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0106", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "106", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0107", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "107", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0108", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "108", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0109", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "109", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0110", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "110", "name": "Harness", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0111", "serie": null, "status": "Available", "qty": 1, "value": 350.0, "hasCalibration": false},
  {"code": "111", "name": "Capacete - Casco", "brand": "N/I", "category": "Tool", "type": "Rope Access", "tag": "0112", "serie": null, "status": "Available", "qty": 1, "value": 30.0, "hasCalibration": false},
  {"code": "112", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0113", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "113", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0114", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "114", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0115", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "115", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0116", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "116", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0117", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "117", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0118", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "118", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0119", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "119", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0120", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "120", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0121", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "121", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0122", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "122", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0123", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "123", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0124", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "124", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0125", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "125", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0126", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "126", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0127", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "127", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0128", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "128", "name": "Capacete - Casco", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0129", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "129", "name": "Grillon 4 m", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0130", "serie": null, "status": "Available", "qty": 1, "value": 150.0, "hasCalibration": false},
  {"code": "130", "name": "Grillon 4 m", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0131", "serie": null, "status": "Available", "qty": 1, "value": 150.0, "hasCalibration": false},
  {"code": "131", "name": "Grillon 4 m", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0132", "serie": null, "status": "Available", "qty": 1, "value": 150.0, "hasCalibration": false},
  {"code": "132", "name": "Grillon 4 m", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0133", "serie": null, "status": "Available", "qty": 1, "value": 150.0, "hasCalibration": false},
  {"code": "133", "name": "Grillon 4 m", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0134", "serie": null, "status": "Available", "qty": 1, "value": 150.0, "hasCalibration": false},
  {"code": "134", "name": "Assento", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0135", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "135", "name": "Assento", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0136", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "136", "name": "Assento", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0137", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "137", "name": "Assento", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0138", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "138", "name": "Polia Dupla Fixa 36Kg", "brand": "Signing Rock", "category": "Tool", "type": "Rope Access", "tag": "0139", "serie": null, "status": "Available", "qty": 1, "value": 65.0, "hasCalibration": false},
  {"code": "139", "name": "Polia Dupla Fixa 36Kg", "brand": "Signing Rock", "category": "Tool", "type": "Rope Access", "tag": "0140", "serie": null, "status": "Available", "qty": 1, "value": 65.0, "hasCalibration": false},
  {"code": "140", "name": "Polia Dupla Fixa 36Kg", "brand": "Signing Rock", "category": "Tool", "type": "Rope Access", "tag": "0141", "serie": null, "status": "Available", "qty": 1, "value": 65.0, "hasCalibration": false},
  {"code": "141", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0142", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "142", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0143", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "143", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0144", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "144", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0145", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "145", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0146", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "146", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0147", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "147", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0148", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "148", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0149", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "149", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0150", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "150", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0151", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "151", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0152", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "152", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0153", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "153", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0154", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "154", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0155", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "155", "name": "Bolsa 54L - Negra", "brand": "Equipo Vertical", "category": "Tool", "type": "Rope Access", "tag": "0156", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "156", "name": "Lixadeira Orbital 4 1/2", "brand": "Dexter", "category": "Tool", "type": "Corded", "tag": "0157", "serie": null, "status": "Available", "qty": 1, "value": 50.0, "hasCalibration": false},
  {"code": "157", "name": "Lixadeira Orbital 4 1/2", "brand": "Dexter", "category": "Tool", "type": "Corded", "tag": "0158", "serie": null, "status": "Available", "qty": 1, "value": 50.0, "hasCalibration": false},
  {"code": "158", "name": "Lixadeira Orbital 4 1/2", "brand": "Dexter", "category": "Tool", "type": "Corded", "tag": "0159", "serie": null, "status": "Available", "qty": 1, "value": 50.0, "hasCalibration": false},
  {"code": "159", "name": "Lixadeira Orbital 4 1/2", "brand": "Dexter", "category": "Tool", "type": "Corded", "tag": "0160", "serie": null, "status": "Available", "qty": 1, "value": 50.0, "hasCalibration": false},
  {"code": "160", "name": "Lixadeira Angular 4 1/2", "brand": "Bosh", "category": "Tool", "type": "Corded", "tag": "0161", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "161", "name": "Lixadeira Angular 4 1/2", "brand": "Bosh", "category": "Tool", "type": "Corded", "tag": "0162", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "162", "name": "Lixadeira Angular 4 1/2", "brand": "Bosh", "category": "Tool", "type": "Corded", "tag": "0163", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "163", "name": "Lixadeira Angular 4 1/2", "brand": "Makita", "category": "Tool", "type": "Corded", "tag": "0164", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "164", "name": "Lixadeira Angular 4 1/2", "brand": "Bosh", "category": "Tool", "type": "Corded", "tag": "0165", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "165", "name": "Lixadeira Angular 4 1/2", "brand": "Bosh", "category": "Tool", "type": "Corded", "tag": "0166", "serie": null, "status": "In Use", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "166", "name": "Lixadeira Angular 4 1/2", "brand": "Dewalt", "category": "Tool", "type": "Corded", "tag": "0167", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "167", "name": "Lixadeira Angular 4 1/2", "brand": "Bosh", "category": "Tool", "type": "Corded", "tag": "0168", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "168", "name": "Lixadeira Angular 4 1/2", "brand": "Bosh", "category": "Tool", "type": "Corded", "tag": "0169", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "169", "name": "Lixadeira Angular 4 1/2", "brand": "Dewalt", "category": "Tool", "type": "Corded", "tag": "0170", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "170", "name": "Lixadeira Orbital 4 1/2", "brand": "Dewalt", "category": "Tool", "type": "Corded", "tag": "0171", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "171", "name": "Lixadeira Angular 4 1/2", "brand": "Makita", "category": "Tool", "type": "Corded", "tag": "0172", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "172", "name": "Lixadeira Orbital 4 1/2", "brand": "Dewalt", "category": "Tool", "type": "Corded", "tag": "0173", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "173", "name": "Lixadeira Orbital 4 1/2", "brand": "Dewalt", "category": "Tool", "type": "Corded", "tag": "0174", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "174", "name": "Lixadeira Orbital 4 1/2", "brand": "Makita", "category": "Tool", "type": "Corded", "tag": "0175", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "175", "name": "Lixadeira Orbital 4 1/2", "brand": "Makita", "category": "Tool", "type": "Corded", "tag": "0176", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "176", "name": "Lixadeira Orbital 4 1/2", "brand": "Makita", "category": "Tool", "type": "Corded", "tag": "0177", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "177", "name": "Lixadeira Orbital 4 1/2", "brand": "Dewalt", "category": "Tool", "type": "Corded", "tag": "0178", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "178", "name": "Lixadeira Orbital 4 1/2", "brand": "Makita", "category": "Tool", "type": "Corded", "tag": "0179", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "179", "name": "Lixadeira Angular 4 1/2", "brand": "Bosh", "category": "Tool", "type": "Corded", "tag": "0180", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "180", "name": "Lixadeira Orbital 4 1/2", "brand": "Dewalt", "category": "Tool", "type": "Corded", "tag": "0181", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "181", "name": "Lixadeira Orbital 4 1/2", "brand": "Makita", "category": "Tool", "type": "Corded", "tag": "0182", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "182", "name": "Furadeira GSB 24-2", "brand": "Bosh", "category": "Tool", "type": "Corded", "tag": "0183", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "183", "name": "Imã 300kg Mod.QZ1-0.3", "brand": "TL-Lift", "category": "Tool", "type": "Corded", "tag": "0185", "serie": null, "status": "Available", "qty": 1, "value": 150.0, "hasCalibration": false},
  {"code": "184", "name": "Carretel Extensão 1.5mm   50metros", "brand": "SuperPower", "category": "Tool", "type": "Electrical", "tag": "0186", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "185", "name": "Carretel Extensão 1.5mm   50metros", "brand": "SuperPower", "category": "Tool", "type": "Electrical", "tag": "0187", "serie": null, "status": "Available", "qty": 1, "value": 60.0, "hasCalibration": false},
  {"code": "186", "name": "Maquina de Solda 200A", "brand": "STAYER", "category": "Tool", "type": "Corded", "tag": "0188", "serie": null, "status": "Available", "qty": 1, "value": 240.0, "hasCalibration": false},
  {"code": "187", "name": "Medidor de Espessura", "brand": "ELCOMETER", "category": "Tool", "type": "Measurement", "tag": "0189", "serie": null, "status": "Available", "qty": 1, "value": 1550.0, "hasCalibration": false},
  {"code": "188", "name": "Medidor de Umidade", "brand": "ELCOMETER", "category": "Tool", "type": "Measurement", "tag": "0190", "serie": null, "status": "Available", "qty": 1, "value": 890.0, "hasCalibration": false},
  {"code": "189", "name": "Furadeira a Bateria", "brand": "Dexter", "category": "Tool", "type": "Corded", "tag": "0191", "serie": null, "status": "Available", "qty": 1, "value": 75.0, "hasCalibration": false},
  {"code": "190", "name": "Furadeira 630W", "brand": "bosh", "category": "Tool", "type": "Corded", "tag": "0192", "serie": null, "status": "Available", "qty": 1, "value": 55.0, "hasCalibration": false},
  {"code": "191", "name": "Tifor 2 ton", "brand": "Topex", "category": "Tool", "type": "Load/Lift", "tag": "0193", "serie": null, "status": "Available", "qty": 1, "value": 40.0, "hasCalibration": false},
  {"code": "192", "name": "Maquina de Alta Pressao K7", "brand": "Karcker", "category": "Tool", "type": "Corded", "tag": "0194", "serie": null, "status": "Available", "qty": 1, "value": 650.0, "hasCalibration": false},
  {"code": "193", "name": "Robot - Caixa De Distribuição 220V", "brand": "Electraline", "category": "Tool", "type": "Electrical", "tag": "0195", "serie": null, "status": "Available", "qty": 1, "value": 85.0, "hasCalibration": false},
  {"code": "194", "name": "Robot - Caixa De Distribuição 220V", "brand": "Electraline", "category": "Tool", "type": "Electrical", "tag": "0196", "serie": null, "status": "Available", "qty": 1, "value": 85.0, "hasCalibration": false},
  {"code": "195", "name": "Aspirador 1400W 220V", "brand": "Cevik Pro", "category": "Tool", "type": "Corded", "tag": "0197", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "196", "name": "Roller Coaster", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0198", "serie": null, "status": "Available", "qty": 1, "value": 130.0, "hasCalibration": false},
  {"code": "197", "name": "Roller Coaster", "brand": "PETZEL", "category": "Tool", "type": "Rope Access", "tag": "0199", "serie": null, "status": "Available", "qty": 1, "value": 130.0, "hasCalibration": false},
  {"code": "198", "name": "Medidor de Espessura", "brand": "UNIT", "category": "Tool", "type": "Measurement", "tag": "0200", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "199", "name": "Carregador Radios", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0201", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "200", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0202", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "201", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0203", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "202", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0204", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "203", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0205", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "204", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0206", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "205", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0207", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "206", "name": "Amoladora Recta", "brand": "Makita", "category": "Tool", "type": "Corded", "tag": "0208", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "207", "name": "Amoladora Recta", "brand": "Makita", "category": "Tool", "type": "Corded", "tag": "0209", "serie": null, "status": "Available", "qty": 1, "value": 200.0, "hasCalibration": false},
  {"code": "208", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0210", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "209", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0211", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "210", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0212", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "211", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0213", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "212", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0214", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "213", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0215", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "214", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0216", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "215", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0217", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "216", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0218", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "217", "name": "Walkie Talkie", "brand": "Retrevis", "category": "Tool", "type": "Communication", "tag": "0219", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "219", "name": "Carregador Radios", "brand": "Retrevis", "category": "Tool", "type": "Comunication", "tag": "0221", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "220", "name": "Carregador Radios", "brand": "Retrevis", "category": "Tool", "type": "Comunication", "tag": "0222", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "221", "name": "Agulheiro Tipo Pistola", "brand": "Sempo", "category": "Tool", "type": "Pneumatics", "tag": "0223", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "222", "name": "Agulheiro Tipo Pistola", "brand": "Sempo", "category": "Tool", "type": "Pneumatics", "tag": "0224", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "223", "name": "Agulheiro Tipo Pistola", "brand": "Sempo", "category": "Tool", "type": "Pneumatics", "tag": "0225", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "224", "name": "Agulheiro Tipo Pistola", "brand": "trelawny", "category": "Tool", "type": "Pneumatics", "tag": "0226", "serie": null, "status": "Available", "qty": 1, "value": 150.0, "hasCalibration": false},
  {"code": "225", "name": "Agulheiro Tipo Pistola", "brand": "trelawny", "category": "Tool", "type": "Pneumatics", "tag": "0227", "serie": null, "status": "Available", "qty": 1, "value": 150.0, "hasCalibration": false},
  {"code": "226", "name": "Picador Sicel", "brand": "Engersol", "category": "Tool", "type": "Pneumatics", "tag": "0228", "serie": null, "status": "Available", "qty": 1, "value": 100.0, "hasCalibration": false},
  {"code": "227", "name": "Agulheiro Tipo Pistola", "brand": "Druckluft", "category": "Tool", "type": "Pneumatics", "tag": "0229", "serie": null, "status": "Available", "qty": 1, "value": 80.0, "hasCalibration": false},
  {"code": "228", "name": "Furadeira a Bateria", "brand": "Dexter", "category": "Tool", "type": "Cordless", "tag": "0230", "serie": null, "status": "Available", "qty": 1, "value": 75.0, "hasCalibration": false},
  {"code": "229", "name": "Tifor 2 ton", "brand": "Topex", "category": "Tool", "type": "Load/Lift", "tag": "0231", "serie": null, "status": "Available", "qty": 1, "value": 40.0, "hasCalibration": false},
  {"code": "230", "name": "Tifor 2 ton", "brand": "Topex", "category": "Tool", "type": "Load/Lift", "tag": "0232", "serie": null, "status": "Available", "qty": 1, "value": 40.0, "hasCalibration": false},
  {"code": "231", "name": "Tifor 2 ton", "brand": "Topex", "category": "Tool", "type": "Load/Lift", "tag": "0233", "serie": null, "status": "Available", "qty": 1, "value": 40.0, "hasCalibration": false},
  {"code": "232", "name": "Tifor 2 ton", "brand": "Topex", "category": "Tool", "type": "Load/Lift", "tag": "0234", "serie": null, "status": "Available", "qty": 1, "value": 40.0, "hasCalibration": false},
  {"code": "233", "name": "LED 100W", "brand": "GSC", "category": "Tool", "type": "Corded", "tag": "0235", "serie": null, "status": "Available", "qty": 1, "value": 20.0, "hasCalibration": false},
  {"code": "234", "name": "Maquina de Lavar Alta Pressão", "brand": "Comet", "category": "Tool", "type": "Corded", "tag": "0236", "serie": null, "status": "Available", "qty": 1, "value": 4550.0, "hasCalibration": false},
  {"code": "235", "name": "Estrobo 100cm 8 mm", "brand": null, "category": "Tool", "type": "Load/Lift", "tag": "0237", "serie": null, "status": "Available", "qty": 1, "value": 45.0, "hasCalibration": false},
  {"code": "236", "name": "Estrobo 100cm 8 mm", "brand": null, "category": "Tool", "type": "Load/Lift", "tag": "0238", "serie": null, "status": "Available", "qty": 1, "value": 45.0, "hasCalibration": false},
  {"code": "237", "name": "Estrobo 160cm 8 mm", "brand": null, "category": "Tool", "type": "Load/Lift", "tag": "0239", "serie": null, "status": "Available", "qty": 1, "value": 50.0, "hasCalibration": false},
];
